name: lae_lar_mel_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.7
  lottie: ^2.6.0
  flutter_launcher_icons: ^0.13.1
  animate_do: ^2.0.0
  intl_phone_number_input: ^0.7.3+1
  video_player: ^2.7.2
  flick_video_player: ^0.5.0
  transparent_image: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/app_icon_foreground.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf