name: lae_lar_mel_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^2.20.0
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.0.5
  intl: ^0.18.1
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  animate_do: ^2.0.0
  lottie: ^2.6.0
  image_picker: ^1.0.4
  flutter_launcher_icons: ^0.13.1
  intl_phone_number_input: ^0.7.3+1
  country_flags: ^2.1.1
  transparent_image: ^2.0.1
  fluttertoast:
  url_launcher: ^6.1.14
  flutter_phone_direct_caller: ^2.1.1
  share_plus: ^7.2.1
  pinput: ^3.0.1
  flutter_windowmanager: ^0.2.0
  pod_player: ^0.2.1
  syncfusion_flutter_pdfviewer: ^23.1.43
  youtube_player_flutter: ^8.1.2
  shimmer: ^3.0.0
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/app_icon.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/images/app_icon_foreground.png'

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf