// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoIlVoS4mZbqtEMENKjNy1xiqVd-3vLtA',
    appId: '1:141912895768:web:b1c3334db8af6df5116e6d',
    messagingSenderId: '141912895768',
    projectId: 'laelarmelflutter',
    authDomain: 'laelarmelflutter.firebaseapp.com',
    storageBucket: 'laelarmelflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm9GAHb41wC71uSJ5kTIM-OdQXEF9jniI',
    appId: '1:141912895768:android:d423e894aadbb294116e6d',
    messagingSenderId: '141912895768',
    projectId: 'laelarmelflutter',
    storageBucket: 'laelarmelflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqr8VcvGhgvTFHxPITFIXXuNX0il-3O5w',
    appId: '1:141912895768:ios:91c6e2151a668246116e6d',
    messagingSenderId: '141912895768',
    projectId: 'laelarmelflutter',
    storageBucket: 'laelarmelflutter.appspot.com',
    iosBundleId: 'com.example.laeLarMelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqr8VcvGhgvTFHxPITFIXXuNX0il-3O5w',
    appId: '1:141912895768:ios:c242302ff0ced587116e6d',
    messagingSenderId: '141912895768',
    projectId: 'laelarmelflutter',
    storageBucket: 'laelarmelflutter.appspot.com',
    iosBundleId: 'com.example.laeLarMelApp.RunnerTests',
  );
}
